export enum OutputType {
    Any = "Any",
    Number = "Number",
    String = "String",
    Boolean = "Boolean",
    Array = "Array",
    Keys = "Keys",
    ControllerButtons = "ControllerButtons",
    MappingTarget = "MappingTarget",
    Size = "Size",
    Point = "Point",
    Date = "Date",
    Direction = "Direction",
    Window = "Window",
    WindowState = "WindowState",
    Monitor = "Monitor",
    IMEConversionMode = "IME",
}